repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terragrunt-hclfmt
        files: (\.hcl)$
        exclude: (examples/terragrunt\.hcl)$
      - id: shellcheck
        types: [shell]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
        name: Rewrite all Terraform configuration files to a canonical format.
        files: (\.tf)$
        exclude: (\.tfvars)$
